[package]
name = "hermes-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "hermes"
path = "src/main.rs"

[dependencies]
hermes-config = { path = "../hermes-config" }
hermes-cron = { path = "../hermes-cron" }
hermes-session = { path = "../hermes-session" }
flate2 = "1.1.5"
serde_json.workspace = true
serde_yaml.workspace = true
tar = "0.4.44"
